# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Action

permissions: {}

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install kyverno-json and test presence in path
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Install kyverno-json
      uses: ./
    - name: Check install
      run: kyverno-json version
    - name: Check root directory
      shell: bash
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi

  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install kyverno-json with cosign verification and test presence in path
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Install Cosign
      uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0
    - name: Install kyverno-json
      uses: ./
      with:
        verify: true
    - name: Check install
      run: kyverno-json version
    - name: Check root directory
      shell: bash
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi

  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install kyverno-json and test presence in path from GitHub
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Install kyverno-json
      uses: kyverno/action-install-kyverno-json@main
    - name: Check install
      run: kyverno-json version
    - name: Check root directory
      shell: bash
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi

  custom:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install kyverno-json and test presence in path
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Install kyverno-json
      uses: ./
      with:
        release: v0.0.1
    - name: Check install
      run: kyverno-json version
    - name: Check root directory
      shell: bash
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi

  wrong_version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Try to install a wrong version
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Install kyverno-json
      uses: ./
      with:
        release: honk
      continue-on-error: true

  custom_dir:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install kyverno-json and test presence in path
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Install kyverno-json
      uses: ./
      with:
        install-dir: "$HOME/.kyverno-jsontest"
    - name: Check install
      run: kyverno-json version
    - name: Check install dir
      shell: bash
      run: |
        [[ $(dirname "$(which kyverno-json)") == "$HOME/.kyverno-jsontest" ]]
    - name: Check root directory
      shell: bash
      run: |
        [[ -z $(git diff --stat) ]]

  custom_dir_root:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions: {}
    name: Install kyverno-json and test presence in path with custom root dir
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Install kyverno-json
      uses: ./
      with:
        install-dir: /usr/bin
        use-sudo: true
    - name: Check install
      run: kyverno-json version
    - name: Check install dir
      shell: bash
      run: |
        [[ $(dirname "$(which kyverno-json)") == /usr/bin ]]
    - name: Check root directory
      shell: bash
      run: |
        [[ -z $(git diff --stat) ]]

  main:
    permissions: {}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        go_version:
          - '1.21'
    name: Try to install with go ${{ matrix.go_version }}
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: ${{ matrix.go_version }}
        check-latest: true
    - name: Install kyverno-json
      uses: ./
      with:
        release: main
    - name: Check install
      run: kyverno-json version

  test-required:
    needs:
    - default
    - verify
    - release
    - custom
    - wrong_version
    - custom_dir
    - custom_dir_root
    - main
    runs-on: ubuntu-latest
    steps:
    - run: echo "Required jobs success!"
