# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Check actions

permissions: {}

on:
  pull_request:
    branches:
    - 'main'
    - 'release*'

jobs:
  check-required:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@ba37328d4ea95eaf8b3bd6c6cef308f709a5f2ec # v3.0.3
      with:
        allowlist: |
          kyverno/action-install-kyverno-json
